### ISSUE TITLE
Updating to Hugo 0.19 breaks home page layout

### ISSUE THREAD

**Issue by kaitlinnewson** [kishaningithub/hugo-creative-portfolio-theme#12]
I recently updated to Hugo 0.19 (from 0.17), and when I re-built my site that uses this theme, it broke the grid layout on the home page -- the cards were not positioning properly vertically. Reverting back to 0.17 and re-building fixed the issue.

**Comment by kishaningithub** [comment]
Hi @kaitlinnewson i just tried hugo 0.19 in my demo site hosted in amazon s3 and it seems
to work fine.

http://hugo-creative-portfolio.s3-website-us-east-1.amazonaws.com/ 

Let me know if you did anything specific and it would help me debug the issue.

**Comment by gchapron** [comment]
Hello @kishaningithub 

I have not been able to run properly the theme with the latest version of hugo. After struggling quite a while and seeing this page, I installed hugo 0.17 and it suddenly worked. Here the error message I was having with the latest version of hugo:

`macpro-home:mysite Guillaume$ hugo server --theme=hugo-creative-portfolio-theme --buildDrafts
WARNING: Site config's rssURI is deprecated and will be removed in a future release. Set baseName in outputFormats.RSS.
Started building sites ...
ERROR 2017/04/10 14:38:50 Error while rendering "page": template: /Users/Guillaume/Desktop/mysite/themes/hugo-creative-portfolio-theme/layouts/_default/single.html:8:17: executing "/Users/Guillaume/Desktop/mysite/themes/hugo-creative-portfolio-theme/layouts/_default/single.html" at <partial "sidebar.htm...>: error calling partial: template: theme/partials/sidebar.html:13:7: executing "theme/partials/sidebar.html" at <partial "socialButto...>: error calling partial: Partial "socialButtonsInSideBar.html" not found
ERROR 2017/04/10 14:38:50 Error while rendering "home": template: /Users/Guillaume/Desktop/mysite/themes/hugo-creative-portfolio-theme/layouts/index.html:8:17: executing "/Users/Guillaume/Desktop/mysite/themes/hugo-creative-portfolio-theme/layouts/index.html" at <partial "sidebar.htm...>: error calling partial: template: theme/partials/sidebar.html:13:7: executing "theme/partials/sidebar.html" at <partial "socialButto...>: error calling partial: Partial "socialButtonsInSideBar.html" not found`

Thanks for making this theme!

**Comment by kaitlinnewson** [comment]
I tried again this morning, and am getting a similar error message to @gchapron after updating to Hugo v 0.20 (via homebrew).

**Comment by kishaningithub** [comment]
Can you check if `layouts/partials/socialButtonsInSideBar.html` is present
inside your `themes/hugo-creative-portfolio-theme` folder ?  The error says its not 
present but it is there in my repo `https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/master/layouts/partials/socialButtonsInSideBar.html`

If its not present can you do a `git stash && git pull --rebase` once inside your `themes/hugo-creative-portfolio-theme` directory?

If the issue was not solved can you do a `tree -a` and place the output here?

**Comment by kaitlinnewson** [comment]
Hi @kishaningithub,

The layout is present - here's the result of `tree -a` in the theme folder

```
.
└── hugo-creative-portfolio-theme
    ├── .DS_Store
    ├── .gitignore
    ├── LICENSE
    ├── README.md
    ├── archetypes
    │   ├── default.md
    │   └── portfolio.md
    ├── layouts
    │   ├── .DS_Store
    │   ├── 404.html
    │   ├── _default
    │   │   ├── baseof.html
    │   │   ├── list.html
    │   │   └── single.html
    │   ├── about
    │   │   └── single.html
    │   ├── contact
    │   │   └── single.html
    │   ├── index.html
    │   └── partials
    │       ├── attribution.html
    │       ├── footer.html
    │       ├── head.html
    │       ├── header.html
    │       ├── mobileNavToggle.html
    │       ├── portfolio.html
    │       ├── scripts.html
    │       ├── sidebar.html
    │       ├── socialButtonsInContact.html
    │       └── socialButtonsInSideBar.html
    ├── static
    │   ├── css
    │   │   ├── bootstrap.min.css
    │   │   ├── bootstrap.min.css.map
    │   │   ├── custom.css
    │   │   ├── font-awesome.min.css
    │   │   ├── fonts
    │   │   │   ├── FontAwesome.otf
    │   │   │   ├── fontawesome-webfont.eot
    │   │   │   ├── fontawesome-webfont.svg
    │   │   │   ├── fontawesome-webfont.ttf
    │   │   │   ├── fontawesome-webfont.woff
    │   │   │   └── fontawesome-webfont.woff2
    │   │   ├── helper.css
    │   │   ├── owl.carousel.css
    │   │   ├── owl.theme.css
    │   │   ├── owl.transitions.css
    │   │   ├── style.blue.css
    │   │   ├── style.default.css
    │   │   ├── style.green.css
    │   │   ├── style.pink.css
    │   │   ├── style.red.css
    │   │   ├── style.sea.css
    │   │   └── style.violet.css
    │   └── js
    │       ├── bootstrap.min.js
    │       ├── ekko-lightbox.js
    │       ├── front.js
    │       ├── imagesloaded.pkgd.min.js
    │       ├── jquery.cookie.js
    │       ├── jquery.min.js
    │       ├── jquery.scrollTo.min.js
    │       ├── main.js
    │       ├── masonry.pkgd.min.js
    │       └── owl.carousel.min.js
    └── theme.toml
```

**Comment by kaitlinnewson** [comment]
I just tried creating a new site with the theme and the examplesite, and I'm getting the same error in v0.20 when running `hugo server`, in case that's helpful.

**Comment by kaitlinnewson** [comment]
FYI, it looks like this issue is isolated to v0.20, as it works fine when I switch to v0.19.

**Comment by kaitlinnewson** [comment]
Here's a screenshot of my original issue with the tile display. I'm not seeing it when I use the example site, but am on my own site. [The code is available here.](https://github.com/scholarsportal/historical-topos)

![topo_image_bug](https://cloud.githubusercontent.com/assets/6903515/24915816/358b32d2-1ea6-11e7-8bcd-1ccdfc2d0f63.png)

**Comment by kishaningithub** [comment]
@kaitlinnewson Thanks a ton for the detailed explanation of the issue!

Hugo doesn't seem to like camelCase anymore :-P for filenames hence changed to snake case

Have fixed the theme in this [commit](https://github.com/kishaningithub/hugo-creative-portfolio-theme/commit/a82dfd5350649aa95bc67463de645caea6c67d7d) and have sent you a [PR](https://github.com/scholarsportal/historical-topos/pull/1)

After the fix this is how your site looked in my dev machine (Layout seems fine)
<img width="1424" alt="screen shot 2017-04-12 at 11 24 50 am" src="https://cloud.githubusercontent.com/assets/763760/24943189/f68c085e-1f72-11e7-9d8d-8d305c6b489d.png">

**Comment by kaitlinnewson** [comment]
@kishaningithub Thanks so much for your help! [Here's our live site with the theme](http://ocul.on.ca/topomaps/), in case you're wondering how it's being used :)
