### ISSUE TITLE
Images are distorted on web server

### ISSUE THREAD

**Issue by namitamo** [kishaningithub/hugo-creative-portfolio-theme#13]
On my localserver everything looks good. When I deploy (the public folder) to dreamhost www.namitamohandas.com , all the images have weird coloured bars across them. I've optimised the images to the container width.
The images are loaded by an img partial.

I've tried various kind of image profiles and optimisation techniques but nothing seems to solve it. Help

**Comment by kishaningithub** [comment]
@namitamo Images look perfectly fine in my desktop browser (Screenshot below)

![screen shot 2017-04-12 at 6 50 15 pm](https://cloud.githubusercontent.com/assets/763760/24959833/7555ed38-1fb1-11e7-8162-c9d152be3551.png)

**Comment by kishaningithub** [comment]
Also i see font awesome is not being loaded.. There seems to be an issue here (Screenshot below)

You have commented carousels() but not the place where it was called in `front.js`

<img width="545" alt="screen shot 2017-04-12 at 6 59 08 pm" src="https://cloud.githubusercontent.com/assets/763760/24960071/3f77cf32-1fb2-11e7-9565-814f1c45b460.png">

**Comment by namitamo** [comment]
@kishaningithub Oh but the images are messed up
![7555ed38-1fb1-11e7-8162-c9d152be3551](https://cloud.githubusercontent.com/assets/15404651/24960309/031c0962-1fb3-11e7-8c7b-40e3484c81b1.png)

And yea I've been trying to figure why the font isn't loading -- let me try and fix that, thanks

**Comment by namitamo** [comment]
@kishaningithub the images don't seem to have the same issue when I use theme elsewhere (wordpress on the same server, and a few other CMSs.

**Comment by namitamo** [comment]
@kishaningithub ahh figured out what the problem was - I'd switched my FTP file transfer type to ASCII for my .htaccess - and forgot to switch it back to binary. This was corrupting the font and image files, resulting in all my troubles. It's all fixed now, thanks.
