### ISSUE TITLE
Example site About and Contact pages not displaying

### ISSUE THREAD

**Issue by deansallinen** [kishaningithub/hugo-creative-portfolio-theme#14]
I was unable to view the About and Contact pages until moving them out from "content/about/index.md" and renaming them to "content/about.md". 

You can see this on the demo page: https://themes.gohugo.io//theme/hugo-creative-portfolio-theme/about/

**Comment by kishaningithub** [comment]
@deansallinen This is an issue in Hugo version 20 and 20.1

Have opened an issue for this [here](https://github.com/spf13/hugoThemes/issues/241)

Thinking whether to put the fix in a backwards compatible way or
to drop backwards compatibility. 🤔
