### ISSUE TITLE
Problems using disqus

### ISSUE THREAD

**Issue by eagle2990** [kishaningithub/hugo-creative-portfolio-theme#16]
I have tried to follow your instructions to use disqus, setting disqusShortname variable, but it's throwing me errors.
I have checked the baseURL (in config.toml) and trusted domains (in disqus), but nothing seems to work. Could you please help me solve this issue?

**Comment by kishaningithub** [comment]
@eagle2990 Just reading the issue.. What was the cause of it?

**Comment by eagle2990** [comment]
Me being an idiot :D. I set up a wrong shortname (misspelled one word). 

Off topic, awesome theme, although I already did some tweaks like allowing using html5 videos instead of just images and a custom.js script.
