### ISSUE TITLE
theme is not applied when actual site is generated

### ISSUE THREAD

**Issue by naveenvhegde** [kishaningithub/hugo-creative-portfolio-theme#2]
when site is served with ```hugo server --buildDrafts``` will serve the page with beautiful theme. But when the public directory is built with command ```hugo -t hugo-creative-portfolio-theme```. Theme is not applied. it looks very native html layout.

**Comment by kishaningithub** [comment]
Hi @naveenvhegde in your `config.toml` what did you specify as your `baseurl` ?

**Comment by naveenvhegde** [comment]
I have specified  "https://deepthys.github.io". But in index.html it is appearing it as below

======
<link href="https://deepthys.github.iocss/style.default.css" rel="stylesheet" id="theme-stylesheet">
======

May be trailing "/" problem ?

**Comment by naveenvhegde** [comment]
I have specified  "https://deepthys.github.io". But in index.html it is appearing it as below

======
href="https://deepthys.github.iocss/style.default.css" rel="stylesheet" id="theme-stylesheet"
======

May be trailing "/" problem ?

**Comment by kishaningithub** [comment]
Its a trailing / issue. Kindly change it to "https://deepthys.github.io/". 

To prevent this in the future modified `baseurl` to  `baseurl = "https://example.org/"` in `config.toml` in the recent [commit](https://github.com/kishaningithub/hugo-creative-portfolio-theme/commit/e3ec8f4cd4e191df5427e274c58680c40a069379)

Thanks for reporting

**Comment by kishaningithub** [comment]
#e3ec8f4cd4e191df5427e274c58680c40a069379

**Comment by kishaningithub** [comment]
e3ec8f4cd4e191df5427e274c58680c40a069379
