### ISSUE TITLE
Feature Request: More pages like the main (masonry) page please ?

### ISSUE THREAD

**Issue by clukeh** [kishaningithub/hugo-creative-portfolio-theme#22]
Hello Kishan,

I really like this theme and I'm slowly getting to understand it and the code, etc. (I am a novice.)

What would be a really good feature would be to have more than just the home page doing the masonry tile 'shuffle'. Ideally, I'd like to be able to add perhaps five or six other pages driven from the sidebar menu (so no drop down / fly out menu requirement) that would point to different 'portfolios' of assets.

Many thanks for the great theme and any ideas you have with this feature request.

Kind regards,

Luke (Derby, UK)

**Comment by GeorgeWL** [comment]
You can do this by creating your own layouts based on the current "portfolio.html" layout btw.

Though I agree, it might be good to have a few extras such as Blog page type that's in the masonry style.

**Comment by clukeh** [comment]
Hi George,
Thanks for the tip. I did have a meddle but couldn't figure out how to replicate the baseof file. Now I know it can be done, I will persevere :-)
Cheers,
Luke

**Comment by clukeh** [comment]
Got there! :-)    Many thanks to Luc-Pascal and George
