### ISSUE TITLE
why single page of portfolio left 1/3 blank for desktop 

### ISSUE THREAD

**Issue by wushuzh** [kishaningithub/hugo-creative-portfolio-theme#25]
Hello,

I love the style of this theme. 

But when click to enter each portfolio page, there is one third of blank on the right.  is it designed in this way (to keep content slim) ? 

Is it possible to have a param or workaround to let content to fill the whole space ?

Best regards,
wushuzh

**Comment by kishaningithub** [comment]
@wushuzh Yup it was designed to be like that. 

If for your use case you need it to be like that, making that change is actually simple
In `layouts/_default/single.html` change the line `<div class="col-lg-8">` in line 5 to `<div class="col-lg-12">`
