### ISSUE TITLE
love the theme but links have error when loaded AWS S3

### ISSUE THREAD

**Issue by keenecarl** [kishaningithub/hugo-creative-portfolio-theme#3]
Thank you for creating this - I attempted building site with it which ran great with hugo server version 17 but when I moved public folder to AWS s3 the links had issue running from AWS.   Take a look at thechinagrove.com  - hope its an easy fix...?

**Comment by kishaningithub** [comment]
Hi @keenecarl It sounds like the bucket contents might not be publicly accessible. [Step 2: Configure Storage on Amazon S3](http://docs.aws.amazon.com/gettingstarted/latest/swh/getting-started-configure-bucket.html) in the S3 documentation talks about how to add a bucket policy which opens up for public access to all files.

If you are planning to use a custom domain name, please note that the bucket name needs to match. So if you want to use www.example.com, that is also supposed to be the name of your bucket.

**Comment by keenecarl** [comment]
Thanks kishaningithub  - I went into AWS and followed step 2 - everyone should be able to access all files but it still does not work...
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Allow Public Access to All Objects",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::aws-website-thechinagrove-240rk/*"
		}
	]
}

grrr ...

**Comment by kishaningithub** [comment]
Hi @keenecarl May be try these answers

https://dmjcomputerservices.com/blog/resolving-403-forbidden-errors-with-amazon-s3/

http://stackoverflow.com/questions/26691286/amazon-s3-bucket-returning-403-forbidden

Im sure this is a S3 config issue

**Comment by keenecarl** [comment]
O.K. - I went thru the files and clicked make public on them all - but changes nothing - any chance you can upload your version to AWS and try?  I think it has to do with the flat dir structure and access to sub directories?  there looks to be programmatic instruction on How access S3 sub directories ...

**Comment by kishaningithub** [comment]
Hi @keenecarl I have successfully deployed in amazon s3. Here is the link

http://hugo-creative-portfolio.s3-website-us-east-1.amazonaws.com/


Here's what i did
1) Uploaded the contents of `public` folder to bucket `hugo-creative-portfolio`
2) Selected all files and folders in the and clicked `Make public` (Screenshot below)
![screen shot 2016-11-13 at 11 16 20](https://cloud.githubusercontent.com/assets/763760/20243899/ff752ea6-a992-11e6-8917-1100738e81f6.png)

**Comment by keenecarl** [comment]
First of all - Thank you for helping me!  --- you are awesome!  Your posted web site allowed me to see that accessing AWS long URL directly worked and that it was a DNS / route 53 configuration issue.  Thank you for your great work.
