### ISSUE TITLE
media queries

### ISSUE THREAD

**Issue by topspinj** [kishaningithub/hugo-creative-portfolio-theme#30]
It would be nice to use media queries to adjust content based on viewport, rather than creating separate html elements for each viewport.

**Comment by kishaningithub** [comment]
@topspinj What exactly do you mean?

**Comment by kishaningithub** [comment]
@topspinj Any updates ?

**Comment by topspinj** [comment]
No, all good, thanks @kishaningithub. Will close this issue now.
