### ISSUE TITLE
Add "black" as optional color scheme?

### ISSUE THREAD

**Issue by elibenton** [kishaningithub/hugo-creative-portfolio-theme#33]
Hello kishaningithub,

Thank you for porting this great theme for hugo. I've really loved working with. I was wondering if you would consider adding black as an optional color scheme in addition to those already available. I understand black was not originally in the bootstrapious theme, but I would love it as an option. 

If this is not possible, I was wondering if you knew of an easy CSS or JS override that I could use to make all the default colors black. Thank you so much for you help! This is my first experience with web development, so I really appreciate any advice.

Eli

**Comment by kishaningithub** [comment]
Create a file `static/css/custom.css` and add in all your custom CSS that you would like for our site.
