### ISSUE TITLE
Links Within Mouseover Text

### ISSUE THREAD

**Issue by FlenserDude** [kishaningithub/hugo-creative-portfolio-theme#36]
Greetings — thanks for a very nice theme.

Question: is it possible to have links within text revealed on mouseover? I would like to avoid having clicks on an item lead to another page, but would like to be able to link directly to external pages. If this doesn't make sense, please ask for clarification.

Thank you!

**Comment by kishaningithub** [comment]
Hi @FlenserDude Thanks!!

I actually want to keep the theme in sync with [bootstrapious](https://bootstrapious.com/p/creative-portfolio)
