### ISSUE TITLE
Description in .Rmd frontmatter not working in portfolio

### ISSUE THREAD

**Issue by marissabarlaz** [kishaningithub/hugo-creative-portfolio-theme#38]
I can't get 'description' in the frontmatter of an Rmd file to show up on the main page of my page - it just shows the first few lines of the content. I have included in the .Rmd file the line description - "blah blah blah" but when I open up the .xml files to see what's going on, it is pulling the description as well as the first few lines of text from the body. This is making the portfolio items have very long text on the homepage.

**Comment by kishaningithub** [comment]
Hi @marissabarlaz Thanks for reporting this issue! 

Will fix it and send a pull request to your repo
