### ISSUE TITLE
Hardcoded Text

### ISSUE THREAD

**Issue by astromberg** [kishaningithub/hugo-creative-portfolio-theme#4]
I'm not sure if you meant for this to be the case, but the text in the sidebar is hardcoded:

https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/d3353596d6e6deca5f1908caa01faf80ae7bbaad/layouts/partials/sidebar.html

Maybe it should be a parameter instead?

**Comment by kishaningithub** [comment]
Yes, It should have been parametrised. I assumed people will always create `layouts/partials/sidebar.html` in their `site directory` to modify the text over there.
Now i feel its a hit on usability. Will fix this
