### ISSUE TITLE
Order of "posts"/portfolio

### ISSUE THREAD

**Issue by robertamezquita** [kishaningithub/hugo-creative-portfolio-theme#45]
Great theme, very lovely port. Firstly, it seems like posts are not displayed (the default rmarkdown post for example I can't find anywhere on an example site). Second, how does it order the portfolio/posts? Is it based on the weight parameter in the header of each post? If not, how can I go about customising this?

**Comment by kishaningithub** [comment]
Hi @robertamezquita Thanks for the complement! :-)

To answer the second question this theme uses default ordering viz. Weight > Date > LinkTitle > FilePath. Its documented [here](https://gohugo.io/templates/lists/#default-weight-date-linktitle-filepath) in hugo docs.

For the first question (i am a bit confused here) the `exampleSite` uses markdown posts and not rmarkdown and its working in [demo site](https://themes.gohugo.io/theme/hugo-creative-portfolio-theme/portfolio/) I will look into blogdown over the week and let you know

**Comment by robertamezquita** [comment]
Woops sorry! Was using R::blogdown and got mixed up with using rmarkdown. Thanks for the answer on ordering, appreciate it!
