### ISSUE TITLE
How to set a preview of the card as a picture downloaded from the network.

### ISSUE THREAD

**Issue by GuaiShu** [kishaningithub/hugo-creative-portfolio-theme#53]
How to set a preview of the card as a picture downloaded from the network.

**Comment by kishaningithub** [comment]
You mean like twitter embeds ?

**Comment by GuaiShu** [comment]
As shown below, I want to get images from other sites, not always local resources. Just like the markdown syntax:
"\!\[description](url)"
![image](https://user-images.githubusercontent.com/14322982/49658820-e420a200-fa7d-11e8-8e88-da58aa230f4c.png)

Thanks!

**Comment by kishaningithub** [comment]
@GuaiShu Thank you for pointing this out. Will fix this.

**Comment by kishaningithub** [comment]
Hi @GuaiShu Have fixed the issue. Try now with the latest version of the template
