### ISSUE TITLE
new installation - blank page

### ISSUE THREAD

**Issue by Hkyx** [kishaningithub/hugo-creative-portfolio-theme#59]
Hi, 

I tried to install the theme in a new hugo website, but the webpage is still blank.
hugo version: Hugo Static Site Generator v0.47.1/extended linux/amd64 BuildDate: 2018-09-25T03:41:10Z

reproduce: 
shell: 
```
- hugo new site test
- cd test
- git clone https://github.com/kishaningithub/hugo-creative-portfolio-theme.git
- rm -rf hugo-creative-portfolio-theme/.git
- cp exampleSite/content, static and config.toml into /test
```
if I inspect html rendered page, no error, no content ...

Any idea? 

Hk

**Comment by kaitlinnewson** [comment]
Is the theme inside of the /themes directory?

**Comment by Hkyx** [comment]
issue solved, 

recreated from start, for the theme sample, instead of moved folder by folder, I moved -R all the example/* to /myHugoWebsite/ seems, one file doesn't moved the times before.

Ty for you help =]
