### ISSUE TITLE
Default social media links don't all work

### ISSUE THREAD

**Issue by ProQuestionAsker** [kishaningithub/hugo-creative-portfolio-theme#6]
When I enter my social media information in the config.toml file, the email works fine, but Twitter re-routes to www.mywebsiteurl/Twitterhandle.  The LinkedIn one doesn't seem to work at all (I entered the entire linkedin address https://www.linkedin/in/username) and an icon doesn't even appear on the site. 

Site available at proquestionasker.github.io

Love the theme, by the way!

**Comment by kishaningithub** [comment]
The theme expects you to put the "full profile url". For twitter try putting `https://twitter.com/Twitterhandle`. For some reason i seem to have missed out `linkedIn` and `stackverflow` in the templates. Will fix that.

Thanks for reporting! :-)

**Comment by ProQuestionAsker** [comment]
Oops! You're absolutely right, I did miss the twitter one.  But thanks for the fast response and fixing the templates 👍
