### ISSUE TITLE
Can't scroll sidebar

### ISSUE THREAD

**Issue by ahmadihamid** [kishaningithub/hugo-creative-portfolio-theme#60]
Sidebar can't be scrolled when having long sidebar about and many social icons so I can't see the nice attribution :)

**Comment by kishaningithub** [comment]
@ahmadihamid Can you provide a link/screenshot ?

**Comment by bodojoko** [comment]
https://youtu.be/NWzgQSTJxow

**Comment by kishaningithub** [comment]
@bodojoko Wow.. Thanks for the video. Will look into it.

**Comment by ahmadihamid** [comment]
Sorry not aware using wrong account
😂

**Comment by ahmadihamid** [comment]
Fixed with :
```
.sidebar-content {
    z-index: 0;
    padding: 0 1.7em 0 0em;
    overflow-y: scroll;
    top: 40px;
    bottom: 0;
    left: 5px;
}
```
