### ISSUE TITLE
Link to the demo is broken

### ISSUE THREAD

**Issue by M4rk9696** [kishaningithub/hugo-creative-portfolio-theme#64]
Link to demo [given](https://themes.gohugo.io/hugo-creative-portfolio-theme/) in the hugo themes page throws 404

Broken link - https://themes.gohugo.io/theme/hugo-creative-portfolio-theme/portfolio/

**Comment by allamiro** [comment]
I also tried to access the demo and its broken

**Comment by kishaningithub** [comment]
Now the demo link is working fine.. closing this issue
