### ISSUE TITLE
Can't load Disqus 

### ISSUE THREAD

**Issue by jpzhangvincent** [kishaningithub/hugo-creative-portfolio-theme#8]
When I was building my website firstly, my blog post wasn't able to load the Disqus comment section. It seems Disqus has a new version of  the universal embed code https://disqus.com/admin/install/platforms/universalcode/. After I manually fixed the index.html file of my file in the public folder, it works. How to fix the mechanism automatically? Where is {{ template "_internal/disqus.html" . }}?

**Comment by kishaningithub** [comment]
Interesting.. The code line importing internal discuss is in layouts/_default/single.html

**Comment by kishaningithub** [comment]
Hi @jpzhangvincent I tried using disqus in the deployed version of the sample site. It seems to be working fine. There is the URL

http://hugo-creative-portfolio.s3-website-us-east-1.amazonaws.com/portfolio/work2/
( I would have commented Hello world for the post)

I think the problem would be something else. 

Would be happy to help if you give me more context.

**Comment by kishaningithub** [comment]
@jpzhangvincent Any updates?

**Comment by jpzhangvincent** [comment]
No worries. It is solved. I'm wondering whether there is a way to show a single page to show the "tags"/"Category" instead of specifying the following

#Adding widgets to the sidebar
  [params.widgets]
    categories = true
    tags = true

**Comment by kishaningithub** [comment]
I personally feel showing "tags" "categories" kind of hamper the overall simplicity of the theme..

By the way great site 
https://jpzhangvincent.github.io/
