### ISSUE TITLE
Google Analytics 4 - Old GA no longer available for new users

### ISSUE THREAD

**Issue by sar111** [kishaningithub/hugo-creative-portfolio-theme#87]
The old system for Google Analytics which used a UA-######### format is no longer available. The new system (Google Analytics 4) uses a new ID code and plugs in differently than the old format. The Hugo boiler plate code for GA hasn't been updated to reflect this, so new users can't use GA with this template.

**Comment by Spcktr** [comment]
You can still access the UA-XXX number by creating a universal GA property.

You just have to click the `Show advanced options` then `Create Universal Analytics property`; select `Create a Universal Analytics property only` while creating the new property.
